import type { BallColorKey, GameState, HeadBallIndex, LevelConfig } from "../types/game";

function getHeadColor(levelConfig: LevelConfig, headIndex: HeadBallIndex): BallColorKey | null {
  return levelConfig.ballQueue.balls[headIndex]?.colorKey ?? null;
}

export function createLevel3InitialGameState(levelConfig: LevelConfig): GameState {
  const balls = levelConfig.ballQueue.balls.map((ball) => ({
    ...ball,
    position: { ...ball.position },
  }));
  const headIndex = levelConfig.ballQueue.headIndex;
  const currentHeadColor = getHeadColor(levelConfig, headIndex);

  return {
    levelId: levelConfig.id,
    status: "ready",
    viewport: { ...levelConfig.viewport },
    playfield: {
      ...levelConfig.playfield,
      center: { ...levelConfig.playfield.center },
      rect: { ...levelConfig.playfield.rect },
      borders: levelConfig.playfield.borders.map((border) => ({
        ...border,
        bounds: { ...border.bounds },
        segments: border.segments.map((segment) => ({ ...segment })),
      })),
    },
    ballQueue: {
      ...levelConfig.ballQueue,
      headAnchor: { ...levelConfig.ballQueue.headAnchor },
      headIndex,
      balls,
    },
    headIndex,
    currentHeadColor,
    isInputLocked: false,
    elapsedTimeMs: 0,
    elapsedTimeSeconds: 0,
    timerStartedAt: null,
    isTimerRunning: false,
    finalElapsedTimeMs: null,
    finalElapsedTimeSeconds: null,
    hp: levelConfig.gameplay.initialHp,
    inputConfig: {
      holdStillMaxMs: levelConfig.gameplay.input.holdStillMaxMs,
      directionDebounceAxisDelta: levelConfig.gameplay.input.directionDebounceAxisDelta,
      redirectCooldownMs: levelConfig.gameplay.input.redirectCooldownMs,
    },
    tuningConfig: {
      swipeLaunch: {
        minSpeed: levelConfig.gameplay.tuning.swipeLaunch.minSpeed,
        maxSpeed: levelConfig.gameplay.tuning.swipeLaunch.maxSpeed,
        minSwipeDistance: levelConfig.gameplay.tuning.swipeLaunch.minSwipeDistance,
        maxSwipeDistance: levelConfig.gameplay.tuning.swipeLaunch.maxSwipeDistance,
      },
      projectile: {
        enabled: levelConfig.gameplay.tuning.projectile.enabled,
        gravity: { ...levelConfig.gameplay.tuning.projectile.gravity },
        maxSubstepMs: levelConfig.gameplay.tuning.projectile.maxSubstepMs,
        bounceRestitution: levelConfig.gameplay.tuning.projectile.bounceRestitution,
      },
      borderImpactShake: {
        enabled: levelConfig.gameplay.tuning.borderImpactShake.enabled,
        light: { ...levelConfig.gameplay.tuning.borderImpactShake.light },
        medium: { ...levelConfig.gameplay.tuning.borderImpactShake.medium },
      },
      stageFrameMismatchGlow: {
        enabled: levelConfig.gameplay.tuning.stageFrameMismatchGlow.enabled,
        color: levelConfig.gameplay.tuning.stageFrameMismatchGlow.color,
        peakOpacity: levelConfig.gameplay.tuning.stageFrameMismatchGlow.peakOpacity,
        edgeWidthPx: levelConfig.gameplay.tuning.stageFrameMismatchGlow.edgeWidthPx,
        blurPx: levelConfig.gameplay.tuning.stageFrameMismatchGlow.blurPx,
        spreadPx: levelConfig.gameplay.tuning.stageFrameMismatchGlow.spreadPx,
        durationMs: levelConfig.gameplay.tuning.stageFrameMismatchGlow.durationMs,
        easing: levelConfig.gameplay.tuning.stageFrameMismatchGlow.easing,
      },
      cameraFollow: {
        enabled: levelConfig.gameplay.tuning.cameraFollow.enabled,
        launchOnlyAfterStart: levelConfig.gameplay.tuning.cameraFollow.launchOnlyAfterStart,
        deadZonePx: levelConfig.gameplay.tuning.cameraFollow.deadZonePx,
        maxOffsetX: levelConfig.gameplay.tuning.cameraFollow.maxOffsetX,
        maxOffsetY: levelConfig.gameplay.tuning.cameraFollow.maxOffsetY,
        followLerp: levelConfig.gameplay.tuning.cameraFollow.followLerp,
        returnLerp: levelConfig.gameplay.tuning.cameraFollow.returnLerp,
      },
      borderImpactRing: {
        enabled: levelConfig.gameplay.tuning.borderImpactRing.enabled,
        strokeWidth: levelConfig.gameplay.tuning.borderImpactRing.strokeWidth,
        startScale: levelConfig.gameplay.tuning.borderImpactRing.startScale,
        endScale: levelConfig.gameplay.tuning.borderImpactRing.endScale,
        durationMs: levelConfig.gameplay.tuning.borderImpactRing.durationMs,
        easing: levelConfig.gameplay.tuning.borderImpactRing.easing,
        alphaFade: levelConfig.gameplay.tuning.borderImpactRing.alphaFade,
      },
      matchImpactParticles: {
        enabled: levelConfig.gameplay.tuning.matchImpactParticles.enabled,
        particleCount: levelConfig.gameplay.tuning.matchImpactParticles.particleCount,
        initialSpeedMin: levelConfig.gameplay.tuning.matchImpactParticles.initialSpeedMin,
        initialSpeedMax: levelConfig.gameplay.tuning.matchImpactParticles.initialSpeedMax,
        scatterAngleDeg: levelConfig.gameplay.tuning.matchImpactParticles.scatterAngleDeg,
        lifetimeMs: levelConfig.gameplay.tuning.matchImpactParticles.lifetimeMs,
        sizeMin: levelConfig.gameplay.tuning.matchImpactParticles.sizeMin,
        sizeMax: levelConfig.gameplay.tuning.matchImpactParticles.sizeMax,
        opacityCurve: levelConfig.gameplay.tuning.matchImpactParticles.opacityCurve,
        useGravity: levelConfig.gameplay.tuning.matchImpactParticles.useGravity,
        gravity: levelConfig.gameplay.tuning.matchImpactParticles.gravity,
        useDamping: levelConfig.gameplay.tuning.matchImpactParticles.useDamping,
        damping: levelConfig.gameplay.tuning.matchImpactParticles.damping,
      },
      softBall: {
        enabled: levelConfig.gameplay.tuning.softBall.enabled,
        headOnly: levelConfig.gameplay.tuning.softBall.headOnly,
        maxSquash: levelConfig.gameplay.tuning.softBall.maxSquash,
        maxStretch: levelConfig.gameplay.tuning.softBall.maxStretch,
        reboundDurationMs: levelConfig.gameplay.tuning.softBall.reboundDurationMs,
        overshoot: levelConfig.gameplay.tuning.softBall.overshoot,
        jellyWobbleStrength: levelConfig.gameplay.tuning.softBall.jellyWobbleStrength,
        secondaryBounceDurationMs: levelConfig.gameplay.tuning.softBall.secondaryBounceDurationMs,
        minTriggerSpeed: levelConfig.gameplay.tuning.softBall.minTriggerSpeed,
        launchIntensity: levelConfig.gameplay.tuning.softBall.launchIntensity,
        redirectIntensity: levelConfig.gameplay.tuning.softBall.redirectIntensity,
        impactIntensity: levelConfig.gameplay.tuning.softBall.impactIntensity,
        specialBounceIntensity: levelConfig.gameplay.tuning.softBall.specialBounceIntensity,
        followerScale: levelConfig.gameplay.tuning.softBall.followerScale,
        wobbleCycles: levelConfig.gameplay.tuning.softBall.wobbleCycles,
        wobbleRotationDeg: levelConfig.gameplay.tuning.softBall.wobbleRotationDeg,
      },
      resultConfetti: {
        enabled: levelConfig.gameplay.tuning.resultConfetti.enabled,
        launcherCount: levelConfig.gameplay.tuning.resultConfetti.launcherCount,
        burstCount: levelConfig.gameplay.tuning.resultConfetti.burstCount,
        speedMin: levelConfig.gameplay.tuning.resultConfetti.speedMin,
        speedMax: levelConfig.gameplay.tuning.resultConfetti.speedMax,
        spreadAngleDeg: levelConfig.gameplay.tuning.resultConfetti.spreadAngleDeg,
        lifetimeMs: levelConfig.gameplay.tuning.resultConfetti.lifetimeMs,
        gravity: levelConfig.gameplay.tuning.resultConfetti.gravity,
        spinSpeedMin: levelConfig.gameplay.tuning.resultConfetti.spinSpeedMin,
        spinSpeedMax: levelConfig.gameplay.tuning.resultConfetti.spinSpeedMax,
        palette: [...levelConfig.gameplay.tuning.resultConfetti.palette],
        resultUiRevealDelayMs: levelConfig.gameplay.tuning.resultConfetti.resultUiRevealDelayMs,
        sizeMin: levelConfig.gameplay.tuning.resultConfetti.sizeMin,
        sizeMax: levelConfig.gameplay.tuning.resultConfetti.sizeMax,
        endSizeScale: levelConfig.gameplay.tuning.resultConfetti.endSizeScale,
        launcherInsetPx: levelConfig.gameplay.tuning.resultConfetti.launcherInsetPx,
        bottomOffsetPx: levelConfig.gameplay.tuning.resultConfetti.bottomOffsetPx,
      },
    },
    input: {
      lastInputDirection: null,
      lastInputVector: { x: 0, y: 0 },
      lastInputAt: null,
      inputCount: 0,
      pointer: {
        isPointerActive: false,
        pointerStart: null,
        lastPointer: null,
        pointerType: null,
        pointerStartedAt: null,
        currentDistance: 0,
        currentThreshold: null,
        hasReachedThreshold: false,
        hasTriggeredInCurrentGesture: false,
      },
    },
    motion: {
      isLaunched: false,
      velocity: { x: 0, y: 0 },
      gravity: levelConfig.gameplay.tuning.projectile.enabled
        ? { ...levelConfig.gameplay.tuning.projectile.gravity }
        : { x: 0, y: 0 },
      maxSubstepMs: levelConfig.gameplay.tuning.projectile.maxSubstepMs,
      bounceRestitution: levelConfig.gameplay.tuning.projectile.bounceRestitution,
      currentVector: null,
      currentSpeed: 0,
      lastTickAt: null,
      lastRedirectAt: null,
      redirectCooldownMs: levelConfig.gameplay.input.redirectCooldownMs,
      isRedirectCooling: false,
      lastAcceptedVector: null,
      headPath: balls.map((ball) => ({ ...ball.position })),
      maxQueueStretch: 0,
    },
    collision: {
      lastCollisionBorderId: null,
      lastCollisionSide: null,
      lastCollisionSegmentIndex: null,
      lastCollisionType: null,
      lastCollisionBorderColor: null,
      lastCollisionHeadColor: null,
      lastReflectionBefore: null,
      lastReflectionAfter: null,
    },
    progress: {
      combo: 0,
    },
    rule: {
      delayedBorderState: "idle",
      pendingBorderId: null,
      pendingBorderSide: null,
      pendingBorderSegmentIndex: null,
      pendingBorderColor: null,
      specialBounceTriggered: false,
      lastSpecialBounceBorderId: null,
      lastRemovedBallId: null,
      lastRemovedBallOrder: null,
    },
    failReason: null,
    clearReason: null,
  };
}
